version: '3.8'

services:
  chat-producer:
    build: ./chat-producer
    container_name: chat-producer
    ports:
      - "8090:8090"
    networks:
      - chatnet

  chat-consumer:
    build: ./chat-consumer
    container_name: chat-consumer
    ports:
      - "8091:8091"
    networks:
      - chatnet

  nginx:
    image: nginx:latest
    container_name: local-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - chat-producer
      - chat-consumer
    networks:
      - chatnet

networks:
  chatnet:
