server {
    listen 80;
    server_name localhost;

    location / {
        proxy_pass http://chat-producer:8090;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/message/ {
        proxy_pass http://chat-consumer:8091/api/message/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /ws-stomp {
        proxy_pass http://chat-producer:8090/ws-stomp;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
}
